//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeePass.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeePass.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Developer&apos;s Blog (News &amp; Feedback):.
        /// </summary>
        public static string About_Blog {
            get {
                return ResourceManager.GetString("About_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Libraries used/referenced:.
        /// </summary>
        public static string About_Libraries {
            get {
                return ResourceManager.GetString("About_Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string About_Purchase {
            get {
                return ResourceManager.GetString("About_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string About_Review {
            get {
                return ResourceManager.GetString("About_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Source Code:.
        /// </summary>
        public static string About_Source_Code {
            get {
                return ResourceManager.GetString("About_Source_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Pass Version: {0}.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string AnalyticsSettings_PageTitle {
            get {
                return ResourceManager.GetString("AnalyticsSettings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Pass collects usage information in order to continuously enhance user experience.
        ///
        ///The collection information will never have your database information, or any information that can directly identify you. However:
        ///- 7Pass does collect your installation ID to link information sent from your device together. This changes everytime 7Pass is installed.
        ///- Usage collection uses very little network traffic, but the cost to your bill may add up if you&apos;re on a capped plan.
        ///
        ///The collected information will be ve [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AnalyticsSettings_Policy {
            get {
                return ResourceManager.GetString("AnalyticsSettings_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Database.
        /// </summary>
        public static string Download_Demo {
            get {
                return ResourceManager.GetString("Download_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Database.
        /// </summary>
        public static string Download_PageTitle {
            get {
                return ResourceManager.GetString("Download_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Server.
        /// </summary>
        public static string Download_Web {
            get {
                return ResourceManager.GetString("Download_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DropBox_Email {
            get {
                return ResourceManager.GetString("DropBox_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DropBox_Password {
            get {
                return ResourceManager.GetString("DropBox_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use phone browser.
        /// </summary>
        public static string EntryDetails_ExternalBrowser {
            get {
                return ResourceManager.GetString("EntryDetails_ExternalBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use integrated browser.
        /// </summary>
        public static string EntryDetails_IntegratedBrowser {
            get {
                return ResourceManager.GetString("EntryDetails_IntegratedBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string EntryDetails_Notes {
            get {
                return ResourceManager.GetString("EntryDetails_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string EntryDetails_PageTitle {
            get {
                return ResourceManager.GetString("EntryDetails_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EntryDetails_Password {
            get {
                return ResourceManager.GetString("EntryDetails_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string EntryDetails_Title {
            get {
                return ResourceManager.GetString("EntryDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string EntryDetails_Url {
            get {
                return ResourceManager.GetString("EntryDetails_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string EntryDetails_Username {
            get {
                return ResourceManager.GetString("EntryDetails_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string EntryFields_PageTitle {
            get {
                return ResourceManager.GetString("EntryFields_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string EntryNotes_PageTitle {
            get {
                return ResourceManager.GetString("EntryNotes_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        public static string GlobalPass_Confirm {
            get {
                return ResourceManager.GetString("GlobalPass_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Password.
        /// </summary>
        public static string GlobalPass_PageTitle {
            get {
                return ResourceManager.GetString("GlobalPass_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global password.
        /// </summary>
        public static string GlobalPass_Password {
            get {
                return ResourceManager.GetString("GlobalPass_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Password.
        /// </summary>
        public static string GlobalPassVerify_PageTitle {
            get {
                return ResourceManager.GetString("GlobalPassVerify_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password to unlock 7Pass.
        /// </summary>
        public static string GlobalPassVerify_Prompt {
            get {
                return ResourceManager.GetString("GlobalPassVerify_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string GroupDetails_Delete {
            get {
                return ResourceManager.GetString("GroupDetails_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string GroupDetails_History {
            get {
                return ResourceManager.GetString("GroupDetails_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move.
        /// </summary>
        public static string GroupDetails_Move {
            get {
                return ResourceManager.GetString("GroupDetails_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string GroupDetails_Rename {
            get {
                return ResourceManager.GetString("GroupDetails_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear keyfile.
        /// </summary>
        public static string MainPage_ClearKeyfile {
            get {
                return ResourceManager.GetString("MainPage_ClearKeyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear password.
        /// </summary>
        public static string MainPage_ClearPassword {
            get {
                return ResourceManager.GetString("MainPage_ClearPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string MainPage_Delete {
            get {
                return ResourceManager.GetString("MainPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download keyfile.
        /// </summary>
        public static string MainPage_DownloadKeyfile {
            get {
                return ResourceManager.GetString("MainPage_DownloadKeyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string MainPage_PageTitle {
            get {
                return ResourceManager.GetString("MainPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin database.
        /// </summary>
        public static string MainPage_Pin {
            get {
                return ResourceManager.GetString("MainPage_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string MainPage_Rename {
            get {
                return ResourceManager.GetString("MainPage_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To.
        /// </summary>
        public static string MoveTarget_PageTitle {
            get {
                return ResourceManager.GetString("MoveTarget_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of generated password.
        /// </summary>
        public static string PassGen_Length {
            get {
                return ResourceManager.GetString("PassGen_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PassGen_PageTitle {
            get {
                return ResourceManager.GetString("PassGen_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string PassGen_Results {
            get {
                return ResourceManager.GetString("PassGen_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PassGen_Settings {
            get {
                return ResourceManager.GetString("PassGen_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Key.
        /// </summary>
        public static string Password_PageTitle {
            get {
                return ResourceManager.GetString("Password_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password.
        /// </summary>
        public static string Password_Password {
            get {
                return ResourceManager.GetString("Password_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my Password.
        /// </summary>
        public static string Password_Remember {
            get {
                return ResourceManager.GetString("Password_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename_PageTitle {
            get {
                return ResourceManager.GetString("Rename_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new name for {0}:.
        /// </summary>
        public static string Rename_Prompt {
            get {
                return ResourceManager.GetString("Rename_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_PageTitle {
            get {
                return ResourceManager.GetString("Search_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Data Collection.
        /// </summary>
        public static string Settings_Analytics {
            get {
                return ResourceManager.GetString("Settings_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Password.
        /// </summary>
        public static string Settings_GlobalPass {
            get {
                return ResourceManager.GetString("Settings_GlobalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Recycle Bin.
        /// </summary>
        public static string Settings_HideRecycleBin {
            get {
                return ResourceManager.GetString("Settings_HideRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use integrated browser.
        /// </summary>
        public static string Settings_IntegratedBrwoser {
            get {
                return ResourceManager.GetString("Settings_IntegratedBrwoser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string SkyDriveList_Refresh {
            get {
                return ResourceManager.GetString("SkyDriveList_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server requires authentication.
        /// </summary>
        public static string WebAuth_Authentication {
            get {
                return ResourceManager.GetString("WebAuth_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string WebAuth_Domain {
            get {
                return ResourceManager.GetString("WebAuth_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string WebAuth_Password {
            get {
                return ResourceManager.GetString("WebAuth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string WebAuth_User {
            get {
                return ResourceManager.GetString("WebAuth_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Links.
        /// </summary>
        public static string WebBrowse_PageTitle {
            get {
                return ResourceManager.GetString("WebBrowse_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string WebDavDownload_PageTitle {
            get {
                return ResourceManager.GetString("WebDavDownload_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string WebDavDownload_Password {
            get {
                return ResourceManager.GetString("WebDavDownload_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database URL.
        /// </summary>
        public static string WebDavDownload_Url {
            get {
                return ResourceManager.GetString("WebDavDownload_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string WebDavDownload_Username {
            get {
                return ResourceManager.GetString("WebDavDownload_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string WebDownload_PageTitle {
            get {
                return ResourceManager.GetString("WebDownload_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database URL.
        /// </summary>
        public static string WebDownload_Url {
            get {
                return ResourceManager.GetString("WebDownload_Url", resourceCulture);
            }
        }
    }
}
