//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeePass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeePass.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to replace your database with the Demo database.
        ///
        ///Do you want to continue?.
        /// </summary>
        internal static string ConfirmDemoDb {
            get {
                return ResourceManager.GetString("ConfirmDemoDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the Demo database is &quot;demo&quot;, without quotes..
        /// </summary>
        internal static string DemoDb {
            get {
                return ResourceManager.GetString("DemoDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial period will not be affected when using the Demo database..
        /// </summary>
        internal static string DemoDbTrial {
            get {
                return ResourceManager.GetString("DemoDbTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading your database.
        ///Please make sure that the url is correct.
        ///
        ///.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0:N0}% ....
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial peroid has ended..
        /// </summary>
        internal static string EndOfTrial {
            get {
                return ResourceManager.GetString("EndOfTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file too large..
        /// </summary>
        internal static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection is available.
        ///Please try again later..
        /// </summary>
        internal static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider buying this application to support the author.
        ///
        ///Do you want to buy this app now?.
        /// </summary>
        internal static string NotifyPurchse {
            get {
                return ResourceManager.GetString("NotifyPurchse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Error downloading the database.
        ///Please try again..
        /// </summary>
        internal static string NullDownload {
            get {
                return ResourceManager.GetString("NullDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving database....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for trying 7Pass.
        ///You&apos;re at usage {0} out of {1} available for trial peroid..
        /// </summary>
        internal static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that your phone&apos;s lock screen is password protected.
        ///
        ///Saving your database password without lock screen protection will allow anyone to view your passwords.
        ///
        ///To set lock screen password, please go to Phone&apos;s Settings\lock &amp; wallpaper..
        /// </summary>
        internal static string WarningStorePassword {
            get {
                return ResourceManager.GetString("WarningStorePassword", resourceCulture);
            }
        }
    }
}
