//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeePass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeePass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Add Notes».
        /// </summary>
        internal static string AddNotes {
            get {
                return ResourceManager.GetString("AddNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete database {0}?
        ///
        ///Doing so will only remove {0} from your phone, and will not delete the source file on your server..
        /// </summary>
        internal static string ConfirmDeleteDb {
            get {
                return ResourceManager.GetString("ConfirmDeleteDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Pass has detected a conflict version of the database.
        ///Your local database is now uploaded at:
        ///[{0}]
        ///
        ///If you want to use the other database, please download it separately..
        /// </summary>
        internal static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Conflict.
        /// </summary>
        internal static string ConflictTitle {
            get {
                return ResourceManager.GetString("ConflictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database file is corrupted!.
        /// </summary>
        internal static string CorruptedFile {
            get {
                return ResourceManager.GetString("CorruptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Database.
        /// </summary>
        internal static string DeleteDbTitle {
            get {
                return ResourceManager.GetString("DeleteDbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to pernamently delete the selected {0} {1}?
        ///
        ///This {0} will be deleted forever and cannot be recovered..
        /// </summary>
        internal static string DeletePernamentPrompt {
            get {
                return ResourceManager.GetString("DeletePernamentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete the selected {0} {1}?.
        /// </summary>
        internal static string DeletePrompt {
            get {
                return ResourceManager.GetString("DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of demo database is &quot;demo&quot;, without quotes..
        /// </summary>
        internal static string DemoDbText {
            get {
                return ResourceManager.GetString("DemoDbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Password.
        /// </summary>
        internal static string DemoDbTitle {
            get {
                return ResourceManager.GetString("DemoDbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading your database.
        ///Please make sure that the url is correct.
        ///
        ///.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Download.
        /// </summary>
        internal static string DownloadTitle {
            get {
                return ResourceManager.GetString("DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entry.
        /// </summary>
        internal static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Field(s).
        /// </summary>
        internal static string FieldsLink {
            get {
                return ResourceManager.GetString("FieldsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your global password!.
        /// </summary>
        internal static string GlobalPassPrompt {
            get {
                return ResourceManager.GetString("GlobalPassPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Pass Global password.
        /// </summary>
        internal static string GlobalPassTitle {
            get {
                return ResourceManager.GetString("GlobalPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve specified an incorrect password.
        ///
        ///Please note that 7Pass doesn&apos;t support using Windows account or custom password providers for the master password..
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///It is possible that the server&apos;s SSL certificate is not trused by your phone.
        ///Do you want to read more about this?.
        /// </summary>
        internal static string InvalidCertificate {
            get {
                return ResourceManager.GetString("InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://7pass.wordpress.com/2011/01/09/faq-updated-why-7pass-says-my-database-signature-is-invalid/.
        /// </summary>
        internal static string InvalidCertificateUrl {
            get {
                return ResourceManager.GetString("InvalidCertificateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve selected an invalid/corrupted keyfile..
        /// </summary>
        internal static string InvalidKeyFile {
            get {
                return ResourceManager.GetString("InvalidKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected URL cannot be displayed. If the URL is too long (&gt; 500 characters), try to relocate your resource to another location where the URL is shorter..
        /// </summary>
        internal static string InvalidUrlPrompt {
            get {
                return ResourceManager.GetString("InvalidUrlPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string InvalidUrlTitle {
            get {
                return ResourceManager.GetString("InvalidUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download KeyFile.
        /// </summary>
        internal static string KeyFileTitle {
            get {
                return ResourceManager.GetString("KeyFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a\s+[^&gt;]?href\s?=\s?([&apos;&quot;])([^&apos;&quot;]+).
        /// </summary>
        internal static string LinkRegex {
            get {
                return ResourceManager.GetString("LinkRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string NewGroupTitle {
            get {
                return ResourceManager.GetString("NewGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection is available.
        ///Please try again later...
        /// </summary>
        internal static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is correct and the database seems valid.
        ///Unfortunately, 7Pass encountered an error while reading the database.
        ///
        ///Do you want to send the author a report so that this bug can be fixed in next version?.
        /// </summary>
        internal static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Key.
        /// </summary>
        internal static string PasswordTitle {
            get {
                return ResourceManager.GetString("PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter group name.
        /// </summary>
        internal static string PromptName {
            get {
                return ResourceManager.GetString("PromptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        internal static string RecycleBin {
            get {
                return ResourceManager.GetString("RecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Group.
        /// </summary>
        internal static string RenameTitle {
            get {
                return ResourceManager.GetString("RenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry has been saved successfully!.
        /// </summary>
        internal static string SavedCaption {
            get {
                return ResourceManager.GetString("SavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Entry.
        /// </summary>
        internal static string SavedTitle {
            get {
                return ResourceManager.GetString("SavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Pass has encountered an unexpected error. 7Pass will now exit.
        ///
        ///Is it ok if I create an email so that you can send to me to fix this problem?.
        /// </summary>
        internal static string UnhandledExPrompt {
            get {
                return ResourceManager.GetString("UnhandledExPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooopppppps.
        /// </summary>
        internal static string UnhandledExTitle {
            get {
                return ResourceManager.GetString("UnhandledExTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes.
        ///Do you really want to ignore these changes?.
        /// </summary>
        internal static string UnsavedChange {
            get {
                return ResourceManager.GetString("UnsavedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved change.
        /// </summary>
        internal static string UnsavedChangeTitle {
            get {
                return ResourceManager.GetString("UnsavedChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating of database {0} failed:
        ///{1}.
        /// </summary>
        internal static string UpdateFailure {
            get {
                return ResourceManager.GetString("UpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Update.
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that your phone&apos;s lock screen is password protected.
        ///
        ///Saving your database password without lock screen protection will allow anyone to view your passwords.
        ///
        ///To set lock screen password, please go to Phone&apos;s Settings\lock &amp; wallpaper..
        /// </summary>
        internal static string WarningStorePassword {
            get {
                return ResourceManager.GetString("WarningStorePassword", resourceCulture);
            }
        }
    }
}
